allow user to configure subscriber timeout for input stream
aws/aws-sdk-java-v2 pull request #5017
Opened 2024-03-14 17:21 UTC by benarnao

## Motivation and Context
Change is required when uploading large files via S3 (transfer manager/S# async client). Currently the sequence of events needed to perform this operation:

1) Create a `BlockingInputStreamAsyncRequestBody`
2) Use this body to create the upload
3) Write the input stream to the body

The second step can take longer than 10 seconds (default) for larger uploads.

## Modifications
Allow user to configure this subscriber timeout value.

## Testing
Unit test to verify we can set the timeout now

## Types of changes
It is only exposing the ability to set a value. If user misconfigures the value it could potentially break their software.
Change is backward compatible and does not change the functionality of any existing code

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

2024-03-14 18:14 UTC, zoewangg requested changes

2024-03-14 18:52 UTC, benarnao commented on core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBody.java
> +    Duration subscribeTimeout();
adjusted to match the approach for output stream

2024-03-14 22:26 UTC, zoewangg reviewed
LGTM, thank you for your contribution! Running tests now

2024-03-15 21:27 UTC, zoewangg commented
Close in favor of https://github.com/aws/aws-sdk-java-v2/pull/5020

2024-03-15 21:27 UTC, closed without merging